name: Austrian Appointment Checker

on:
  schedule:
    - cron: '*/45 * * * *'  # Every 30 minutes
  workflow_dispatch:       # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}
      cancel-in-progress: false

    env:
      EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_2_ADDRESS: ${{ secrets.EMAIL_2_ADDRESS }}
      TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
      TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
      TWILIO_SMS_FROM: ${{ secrets.TWILIO_SMS_FROM }}
      TWILIO_SMS_TO: ${{ secrets.TWILIO_SMS_TO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run appointment checker
        run: python appointment_checker.py